title: <p align="center"> Gianluca Cavallaro </p>

logo: "/images/picture.jpg?raw=true"

description:
  <p align="center">
  <a href="documents/CV_Gianluca_Cavallaro.pdf">Resume</a> |
  <a href="www.linkedin.com/in/gianluca-cavallaro">LinkedIn</a> |
  <a href="https://github.com/Gianluca124">GitHub</a>
  </p>
  
  <p align="justify">
  Hi Everyone! 👋 Welcome to <b><i>Gianluca Cavallaro</i></b>'s portfolio website
  <br />
  <p align="center">
  📌 Data Science at <b>University of Milano-Bicocca</b>
  <br />
  </p>
  </p>
  
theme: jekyll-theme-minimal
# google_analytics: G-8Q75V2KGYQ # Google Analytics tracking ID
